### ISSUE TITLE
Proposal !

### ISSUE THREAD

**Issue by Lzhikai** [Lzhikai/siboor-voron#1]
**If there is something wrong, please put forward your suggestion or idea, I will be happy to correct it!**

**Comment by russelryu** [comment]
Can you share the printer.cfg file for voron v0.1 young kit?

**Comment by Lzhikai** [comment]
> 你能分享 voron v0.1 年轻套件的 printer.cfg 文件吗？
Premium and youth versions are universal.

**Comment by Lzhikai** [comment]
> 你能分享voron v0.1年轻套装的printer.cfg文件吗？

都是通用的
